### ISSUE TITLE
Package source is unavailable in DSM

### ISSUE THREAD

**Issue by swcheon** [SynoCommunity/spksrc#2004]
Many people have experienced this situation.
Could you check the repo?

![Screenshot](https://cloud.githubusercontent.com/assets/7111053/11801488/a8d5a2c6-a329-11e5-8190-5a59edfe7fc9.png)

**Comment by Diaoul** [comment]
Which DSM version and model?

**Comment by swcheon** [comment]
@Diaoul DS1515+, DS716+ with DSM 5.2 :)

**Comment by Raptorek** [comment]
Same for me on DS213j (DSM 5.2-5644 Update 1)

**Comment by davidmerrique** [comment]
Yep. Same here. Looks like the DS716+ isn't supported

**Comment by piwi82** [comment]
@swcheon, try using `https` :

`https://packages.synocommunity.com/`

**Comment by davidmerrique** [comment]
@piwi82 Same problem with https:

![screen shot 2015-12-16 at 10 09 10 am](https://cloud.githubusercontent.com/assets/867522/11844525/2b3745b8-a3dd-11e5-8fd3-ebf58f607e10.png)

**Comment by davidmerrique** [comment]
This is a WIP #1944

**Comment by Raptorek** [comment]
For me problem was with Static DNS record in my router. It was historical and forgotten solution of some  problem that SynoCommunity had with domain. So for me is everything working now. :)

**Comment by piwi82** [comment]
@davidmerrique :
* What is the DNS server configured on your NAS ?
* What IP address is resolved by `packages.synocommunity.com` ?

`DiskStation> nslookup packages.synocommunity.com`

**Comment by anyall** [comment]
Hello,

I have the same pb on DS716+

Nslookup packages.synocommunity.com = 176.31.184.40

**Comment by piwi82** [comment]
Some users have solved this problem by removing all repositories and adding SynoCommunity's.

**Comment by Dr-Bean** [comment]
716+ owners should be looking at #1944, not here. Support for that model is not available yet.
That would apply to @swcheon (although you might still have a valid issue wrt your 1515+), @davidmerrique and @anyall.

**Comment by Dr-Bean** [comment]
@swcheon Does the issue with your 1515+ still exist? If so, could you please answer the questions @piwi82 asked [here](https://github.com/SynoCommunity/spksrc/issues/2004#issuecomment-165162069)?

**Comment by DocteurB** [comment]
is back i didn't do anything ...

**Comment by piwi82** [comment]
@Dr-Bean There is no problem with the domain name resolution.
I think `/var/tmp/pkglist.tmp/otherserver` is being corrupted with unofficial repositories. But [my last message](https://github.com/SynoCommunity/spksrc/issues/2004#issuecomment-165486048) has not received any feedback.

**Comment by Dr-Bean** [comment]
I thought that issue occurred only on DSM6 (I assume it's a bug that'll be fixed with the next beta), but it's a good idea to try it regardless. The repo currently does seem to have some availability issues though (502's)

**Comment by h4de5** [comment]
same problem on ds1512+
update of python didnt work, message: "Aktualisierung von "Python" fehlgeschlagen. Dieses Paket wurde von einem unbekannten Herausgeber veröffentlich" - something about publisher is unknown, found that thread, successfully changed the repository to https, now there aren't any SynoCommunity packages in my list anymore and i can't switch back to http.

Message: 
"Invalid location"
or
"Ungültiger Speicherort"

calling the url: http://packages.synocommunity.com/ 
in my browser, sometimes gives an: 502 Bad Gateway
other times: 400 Bad Request

**Comment by piwi82** [comment]
@h4de5 *something about publisher is unknown*

Have you set the Trust Level to *Synology Inc. and trusted publishers* ? (Step 1 in https://synocommunity.com/#easy-install)

**Comment by h4de5** [comment]
yes i had that setting.
i tried now to remove all repositories and added just synocommunity with https - package update and search is working again.
I also think it may be enough to just remove the synocommunity repo and add it again.

**Comment by Dr-Bean** [comment]
With the lack of response from @swcheon, I guess the problem is resolved. 

@swcheon: if the problem still persists after checking the suggestions @piwi82 made earlier, feel free to let us know any time.
