### ISSUE TITLE
Mono 4.6.2.7-8 crashes Sonarr

### ISSUE THREAD

**Issue by darebee** [SynoCommunity/spksrc#2558]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_Mono
_Package Version:_4.6.2.7-8

Sonarr Ver. 2.0.0.4230

_NAS Model:_DS1815+
_NAS Architecture:_Intel
_DSM version:_DSM 6.0.2-8451 Update 6

### Expected behavior
Tell us what should happen. Sonarr should not crash.

### Actual behavior
Tell us what happens instead. Sonarr will start and try to get series and an error occurs:

Unable to set date of file [/volume1/data/Videos/TV.Shows/Amazing Race Canada, The/Season 4/The Amazing Race Canada - S04E10 - We're Doing It Wrong! We're In Big Trouble.mkv]: Access to the path "/volume1/data/Videos/TV.Shows/Amazing Race Canada, The/Season 4/The Amazing Race Canada - S04E10 - We're Doing It Wrong! We're In Big Trouble.mkv" is denied.

System.UnauthorizedAccessException: Access to the path "/volume1/data/Videos/TV.Shows/Amazing Race Canada, The/Season 4/The Amazing Race Canada - S04E10 - We're Doing It Wrong! We're In Big Trouble.mkv" is denied.
  at System.IO.File.SetLastWriteTime (System.String path, System.DateTime lastWriteTime) [0x00029] in /spksrc/native/mono/work-native/mono-4.6.2/mcs/class/corlib/System.IO/File.cs:496 
  at NzbDrone.Common.Disk.DiskProviderBase.FileSetLastWriteTime (System.String path, System.DateTime dateTime) [0x00048] in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Disk\DiskProviderBase.cs:250 
  at NzbDrone.Core.MediaFiles.UpdateEpisodeFileService.ChangeFileDateToLocalAirDate (System.String filePath, System.String fileDate, System.String fileTime) [0x0002b] in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\MediaFiles\UpdateEpisodeFileService.cs:130 
Close

### Steps to reproduce
_1._Sonnar will be in Stopped state
_2._Run Sonarr
_3._within 90 seconds it will stop

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
I'm not sure how to access these logs be will gladly provide if someone explains how to get them. I tried WinSCP but can't get to /usr/ or /var/...

Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by Dr-Bean** [comment]
That's a permissions issue, not really a crash.

Make sure the group `sc-media` has read/write permissions on `/volume1/data/Videos/TV.Shows/`. You can do that via File Manager, and it should look like this:
![rw](https://cloud.githubusercontent.com/assets/1538260/21189657/b2e541de-c21f-11e6-8631-af9f1afbe0d9.png)

In addition, you'll also want to make sure that Sonarr can access the top-level directories (so `data` and `Videos`), and you do that by setting _at least_ the traverse folders permission for _both_ those directories (to be clear, if inheritance is turned on, which is the default setting, setting the permissions on `data` should be sufficient. The permission will apply to `Videos` automatically, you'll see a greyed-out `sc-media` group when you check those permissions)

![traverse](https://cloud.githubusercontent.com/assets/1538260/21189721/ea68b244-c21f-11e6-96d3-907114df54d0.png)

**Comment by darebee** [comment]
Even though this didn't start until after the update to Mono? 

Anyway, I uninstalled Mono and Sonarr (someone recommended I do this) but I can no longer see any SynoCommunity packages in the Package Center. What might I have messed up now?

**Comment by Dr-Bean** [comment]
Sonarr doesn't necessarily care about Mono's version, as long as it's compatible (which, to be clear, is the point of the Mono 4.6 beta package). If Sonarr had proper permissions before, then updating Mono won't change a thing.

File Station is part of DSM, not File Manager...wrong name, apologies for the confusion. Should be available in the DSM GUI.

As for Package Center, no idea. Repository is still up and running. Tried a reboot?

**Comment by Dr-Bean** [comment]
...and then I noticed that you're on DSM6. Sonarr won't be able to run after reinstalling, because you're on DSM6. Our packages are not yet compatible with DSM6, we're in the process of fixing what has been broken.

**Comment by darebee** [comment]
Really? Since when? I've been on DSM 6.0 for quite a few months and it was all working until the Mono update on Monday...

**Comment by Dr-Bean** [comment]
Installation of packages on DSM5 + a subsequent upgrade to DSM6 is not an issue. The problem is with clean installations of packages that create users. Take a look at the open issues on this bugtracker tagged DSM6...

**Comment by darebee** [comment]
Damn, I wish I had read your post prior to someone suggesting I uninstall!!! So now I can't do anything with Sonarr until this is resolved? What if the users are created prior to the install?

**Comment by mrchris76** [comment]
Having same issue, Sonarr stops after around 90secs. Checked (and reapplied) sc-media permissions to both media and download directories on my NAS. Hopefully someone can figure this out soon :(

**Comment by JSLoz** [comment]
Any updates on this? I can't get my Sonarr working again... I have checked all the permissions looks ok as some suggested..

**Comment by mrchris76** [comment]
Is nobody else seeing this?

I'm running Sonarr version 2.0.0.3357 on DSM 5.2-5967 with Mono 4.6.2.7-8.

Sonarr still dies after 60-90 seconds. Permissions all look good still. I still think its the Mono update that caused this but no idea if I can roll back to a previous version.

**Comment by Dr-Bean** [comment]
Again, Mono 4.6 is a beta package. That's for a reason: beta packages can and will break, and we need to know if that happens before we add packages to the stable channel.
If you're not ready for that, don't use beta packages.
Downgrading is not possible. To go back to stable, you will need to uninstall Sonarr, uninstall Mono. Then before going forward, make sure you're on the stable channel (Package Center settings), then install in the opposite order.
Note that on DSM6, Sonarr is still broken...as are almost all other packages. There's no resolution for that right now, things are in progress. Subscribe to #2216 if you want to keep informed.

With that out of the way, I can't reproduce it. Unless one of you can reproduce it with a clean setup, there's not much we can do.

**Comment by mrchris76** [comment]
OK thank you, understood. I actually forgot I had enabled the Beta versions in the package center settings. I will remove and reinstall as suggested and also subscribe to #2216 to keep informed.

Many thanks for your help.

**Comment by Dr-Bean** [comment]
One other thing: if you do test on a clean setup, make sure Sonarr is updated to latest, via the built-in updater that Sonarr provides. If you're actually on 2.0.0.3357, then later updates might make a difference. Master is at 2.0.0.4427 if I'm not mistaken.
With some luck, you might be able to update to latest before Sonarr crashes...

**Comment by JSLoz** [comment]
Ok some how I have manage to uninstall sonarr and mono and reinstalled with beta setting turned off.   And got sonarr working again..  

Now lucky I did backup my sonarr to my local machine.. just have to work out how to copy it back to system and restore it..

**Comment by mrchris76** [comment]
All good now thanks, clean install and restored my old Sonarr config files. I'm up and running again! 👍

**Comment by mrchris76** [comment]
JSLoz check this guide out to restore config:

https://github.com/Sonarr/Sonarr/wiki/Backup-and-Restore

**Comment by JSLoz** [comment]
@mrchris76 thanks..

**Comment by JSLoz** [comment]
Ok I am also 100% back in action..

**Comment by Dr-Bean** [comment]
What I'll do is release an update of the Sonarr package to the latest version...once I get to it. 
@mrchris76 indicated that he was on an outdated Sonarr version, and I know there have been fixes/additions wrt Mono 4.4 versions...not for 4.6 afaik though, but still.
We don't regularly update the Sonarr package, because it has a built-in updater (via system, updates, somewhere in that neighbourhood). You can (and probably should) check on a regular basis if updates are available, if not for Mono compatibility, then for fixes and improvements to Sonarr itself.

**Comment by JSLoz** [comment]
Version
2.0.0.3357
Mono Version
3.10.0 (tarball Sat Mar 28 10:18:33 UTC 2015)

This is what I am running now..

**Comment by Dr-Bean** [comment]
Then you should check if Sonarr has updates available ;)

**Comment by JSLoz** [comment]
I'm too scared to touch anything on it now.. It's working for now.. :)

**Comment by Dr-Bean** [comment]
Well, you have a backup. And unless I'm very much mistaken, Sonarr creates a backup before upgrading.

**Comment by JSLoz** [comment]
Ok... Done!! You're a bad influence..  or good.. I'm not sure yet.. haha

**Comment by JSLoz** [comment]
Version
2.0.0.4427

**Comment by mrchris76** [comment]
I am also now completely up to date. tbh I thought I had to wait for updated packages via Package Center wasn't sure if the in-built updater worked and was afraid to test :)

**Comment by Dr-Bean** [comment]
We would have disabled it completely if we weren't sure :)
Maybe we should put a message in the install wizard, to inform people that they should check it out. How's that?

**Comment by isalas16** [comment]
So I'm having the same issue with Sonarr and mono, I uninstall everything, I disabled beta version but now I cant see mono, if I click on install sonarr I get a message saying mono is missing :S is there somewhere I can download the old mono package before the beta?

**Comment by martin-ericsson** [comment]
This worked for me: 

1. Enable Beta-version in Synology package manager.
2. Install Mono (4.6)
3. Install Sonarr package, start Sonarr
4. When Sonarr is started, go to the Sonarr UI and trigger the update to the latest version (2.0.0.4427)
5. Stop Sonarr.
6. Restore backup.
7. Start Sonarr.

Ie, the latest Sonarr-release (not the one in the package though), seems to work with Mono 4.6

**Comment by MarcoPescatore** [comment]
@martin-ericsson This is what worked for me too! Thanks for sharing

**Comment by isalas16** [comment]
AH! this appears to be working for me as well, I'm in the process of re-adding my library but so far Its been running for a couple of hours, before it wouldn't last 1 min.

**Comment by darebee** [comment]
How do you trigger this update to the lastest Sonarr via the UI? Will this help us DSM 6.0 folks too?

**Comment by MarcoPescatore** [comment]
Sonarr runs for about 30 seconds correct? In this time go to SYSTEM /
UPDATES and click the green button beside  "2.0.0.4427 - 10 Dec 2016" (see
screen shot)
I think the fist click downloaded the new version. Then you probably have
to restart Sonarr again to get another 30 sec. Now click the button again
to install. Done
Good Luck

**Comment by isalas16** [comment]
@darebee  Im on DSM 6.0, when sonarr is installed go into Sonarr gui, click on the system menu, then updates sub menu, there should be button there to install the latest version.

**Comment by darebee** [comment]
Thanks everyone. I have Sonarr up and running and upgraded but if I do my restore of the settings I get the permissions problem again. I am in the process of importing Existing Series on Disk. Once this is all done I will make sure everything is working and respond back.

**Comment by isalas16** [comment]
Just to update, I re-added all my shows and sonarr has been running fine for over 8 hours downloading and managing files.

**Comment by ujellyx** [comment]
@martin-ericsson how does one restore the backup?
I reinstalled mono and Sonarr and after the uninstallation my NAS also seems to have removed the backup files. I downloaded the .zip prior to that, so that's no problem (I do have the config.xml and nzbdrone.db on my harddrive), but i can't write into the backup-/database-folder with my admin-user. The folder's owner is "nzbdrone", so i guess i have to login to that user via SCP? What's the password? Am i missing something here?

**Comment by darebee** [comment]
ujellyx, if you log on using putty and the admin account you should be able to do sudo cp to copy. If prompted for password, it should be your admin password again... It worked for me.

**Comment by ujellyx** [comment]
@darebee didn't work for me unfortunately... i always get permission denied errors, because the folder is owned by a user called "nzbdrone" and i can't write into it even with root-permissions...

**Comment by Zoba273** [comment]
Running the update as well as setting the sc-media permissions fixed the problem for me (after the update it worked again)

**Comment by schumi2004** [comment]
Sonarr runs just fine here except i can't access the GUI, error 500.
Is this related?

**Comment by Dr-Bean** [comment]
@schumi2004 Without any further details/info/logging, I'm going to say "No".

**Comment by Dr-Bean** [comment]
I've published a new version of the Sonarr package, updating it to latest as of now (2.0.0.4472). This should solve issues where an outdated version of Sonarr would have compatibility issues with Mono 4.6.

**Comment by schumi2004** [comment]
@Dr-Bean, Compiled it last night and works perfect.

**Comment by Dr-Bean** [comment]
@schumi2004 You mean you compiled the updated Sonarr package? Cool, thanks for the info.
FYI then, I have made some minor corrections to it. I'll push it in a few minutes.

**Comment by Carpo31** [comment]
My synology updated sonarr to version 20170106-9 and now has stopped working, tried uninstalling and reinstalling and still no luck.

Uninstalled both mono versions (synocomm one and synology one) and reinstalled and tried but still sonarr won't start

**Comment by gotson** [comment]
the new version of Sonarr doesn't start for me.
It seems it's using the SynoCommunity Mono (4.6.2.7-8 located in /usr/local/mono/bin).
Actually when i try to do a `./mono -V` in Mono's folder, i get a segfault.

The mono from Synology (4.2.1 located in /bin/mono) is working fine.
I changed the start-stop-status script to use the Synology Mono instead of the SynoCommunity one, now it works.

**Comment by schumi2004** [comment]
@Dr-Bean, yes compiled your updated version. I saw your update but i don;t think i need them for now. I'll wait until it gets updated in official repo ;)

**Comment by Dr-Bean** [comment]
@schumi2004 It's already part of the current package, I published the package before I pushed the updates to the repo. But, as you say, there's no big changes, so just FYI.

@ other commenters:
- Segfaults when running Mono can be discussed in https://github.com/SynoCommunity/spksrc/issues/2298. 
- People with issues running Sonarr in general: please carefully read my previous comments in this issue. I would also suggest to read https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md, especially if you think that my previous comments here have no bearing on your problem (e.g. running DSM5).
Thanks.

**Comment by EvtK** [comment]
@gotson can you share your configuration? I have problems running sonarr since the last update, and believe it is connected to mono. So far I have tried:

MONO_PATH="/var/packages/Mono/target/usr/bin"
MONO="${MONO_PATH}/mono"

MONO_PATH="/bin"
MONO="${MONO_PATH}/mono"

But Sonarr won't start. Is there anyway to get some logging on this, to see what is going wrong?

thankls

**Comment by remorsehorse** [comment]
Great post on Reddit which explains how to point Sonarr to the old mainstream, non-beta Mono and get it working with DSM6. Have used this method twice after Sonarr updates now:

https://www.reddit.com/r/sonarr/comments/4c7ddp/howto_sonarr_on_synology_dsm_60_workaround/

**Comment by Dr-Bean** [comment]
Locking. I made the situation quite clear in my previous comment, and on top of that, a Mono package for DSM6 has been published which should resolve the segfaults some people have encountered. See #2298.
