### ISSUE TITLE
Request for SynoCommunity membership

### ISSUE THREAD

**Issue by ymartin59** [SynoCommunity/spksrc#2825]
Hello

I request membership to SynoCommunity organisation so that I can help to triage issues, review and eventually accept merge request, and also publish packages to online repository.

My first target is to address issues with Broadwell architecture and DSM 6.1 support: #2509 #2716 #2718 #2813 #2819 #2666 #2727 

As Broadwell will be a new architecture in SynoCommunity repository, packages have to be built for DSM 6.1 only, without doubt about transitioning from 5.x. I agree Broadwell users will do beta-testing but I consider it better than no package being available.

Regards
Yves Martin

**Comment by m4tt075** [comment]
+1

And sincere thanks, @ymartin59, for being willing to step up and offer your support!

**Comment by GuillaumeSmaha** [comment]
+1 too
@ymartin59 Thanks for your help !

**Comment by Safihre** [comment]
Additionally, clean-up/merging of all the issues/PR's would really benefit this project and keep it going strong 👍

**Comment by cytec** [comment]
Adding Broadwell to the repo is one thing. That can be done pretty quickly (if it hasn't already) but getting the 6.x toolchain stuff done would be a huge step forward imho!

**Comment by ymartin59** [comment]
@cytec I already registered with username "ymartin59", so you may grant me rights and provide some information how to proceed with publication

Concerning DSM 6.1 toolchain, I am confident, as I already delivered some native packages on demand to requesters

**Comment by cytec** [comment]
sorry... you'll have to wait for @Diaoul to give you the rights to publish to the repo.

**Comment by Diaoul** [comment]
Done

**Comment by KaraokeStu** [comment]
He lives! 💃

**Comment by ymartin59** [comment]
Thank you but ... what's next ? How should I publish a package properly ? I guess it has to be signed. Is there any documentation about this process ?

**Comment by ymartin59** [comment]
@KaraokeStu please reopen, issue is not fixed from my point of view. I am still not member of GitHub organization: https://github.com/orgs/SynoCommunity/people

**Comment by cytec** [comment]
@ymartin59 signing is handled by the server. Uploading: https://github.com/SynoCommunity/spksrc/wiki/Package-Server#how-does-it-work-for-developers- thought we had something more clear on that but cant happen to find it now... so to sum this up:

1. Login to synocommunity.com 
2. copy your api key
3. run `make setup` in spksrc if you didn't done that already
4. open lokal.mk (i think thats the name of the file)
5. Put in your apikey there
6. run `make publish-xyz` see https://github.com/SynoCommunity/spksrc/wiki/Compile-and-build-rules#spk-rules

**Comment by ymartin59** [comment]
Seems like a permission is lacking... POST method is not allowed ?

```
root@8ac5ecef0528:/spksrc/spk/ncdu# make publish-arch-evansport-6.1
===>  Building and publishing package for arch evansport-6.1
make[1]: Entering directory '/spksrc/spk/ncdu'
(cd /spksrc/spk/ncdu/work-evansport-6.1/staging && tar cpzf /spksrc/spk/ncdu/work-evansport-6.1/package.tgz --owner=root --group=root *)
===>  Creating checksum for ncdu
(cd /spksrc/spk/ncdu/work-evansport-6.1 && tar cpf /spksrc/spk/ncdu/../../packages/ncdu_evansport-6.1_1.12-1.spk --group=root --owner=root package.tgz INFO PACKAGE_ICON.PNG PACKAGE_ICON_256.PNG scripts)
http --verify=no --auth XXXXXXXXXXXXXX: POST https://synocommunity.com/packages @/spksrc/spk/ncdu/../../packages/ncdu_evansport-6.1_1.12-1.spk
HTTP/1.1 405 METHOD NOT ALLOWED
Allow: GET, OPTIONS, HEAD
CF-RAY: 3820c179f83c3e9e-ZRH
Connection: keep-alive
Content-Type: text/html
Date: Fri, 21 Jul 2017 20:02:14 GMT
Server: cloudflare-nginx
Set-Cookie: __cfduid=da8d80430489ec8978a0ab3901dde085f1500667334; expires=Sat, 21-Jul-18 20:02:14 GMT; path=/; domain=.synocommunity.com; HttpOnly
Transfer-Encoding: chunked


http: error: ConnectionError: HTTPSConnectionPool(host='synocommunity.com', port=443): Read timed out.
../../mk/spksrc.spk.mk:295: recipe for target 'publish' failed
make[1]: *** [publish] Error 1
make[1]: Leaving directory '/spksrc/spk/ncdu'
../../mk/spksrc.spk.mk:422: recipe for target 'publish-arch-evansport-6.1' failed
make: [publish-arch-evansport-6.1] Error 2 (ignored)
```

**Comment by cytec** [comment]
6.X isn't supported yet by the repo... try publishing a 5.2 version of the SPK that should do!

**Comment by Diaoul** [comment]
Yep, I have to work on that. DrBean submited a PR for that. The server will most likely break during any update...

**Comment by ymartin59** [comment]
Oups sorry to learn about that server limitation. As there was already 6.0, I registered 6.1 firmware and tried for a small package easy to test on my platform.

May I help on anything ?

**Comment by cytec** [comment]
@ymartin59 afaik the server backend doesn't handle 6.x atm as @Diaoul stated there was a PR for @Dr-Bean which has not been implemented yet :/

**Comment by ymartin59** [comment]
OK so may I implement it ? Where is server source code and installation instruction - for me to setup a testing instance ? What is PR location ?

**Comment by cytec** [comment]
AFAIK: the current code can be found here: https://github.com/Diaoul/spkrepo the PR here https://github.com/Diaoul/spkrepo/pull/8

**Comment by Safihre** [comment]
@cytec @ymartin59 @Dr-Bean @KaraokeStu 
Stupid question maybe, but why not let TravisCI handle the building and publishing to the public? We also used to locally build, but all the hassle of setting up just became too much.

**Comment by ymartin59** [comment]
I already thought about it... and PR #2533 for instance refers to a travis build https://travis-ci.org/torrentalle/spksrc/builds/177990202

So a build on Docker image requires to pass a least minimum arguments: package, target architecture.

If you have ideas about it, do no hesitate to submit an issue with concept and script proposals, maybe as PR if relevant

**Comment by Safihre** [comment]
@ymartin59 Bit too busy with my own projects, was just wondering 😉

**Comment by ymartin59** [comment]
@KaraokeStu @Diaoul @Dr-Bean May you please grant me permissions on SynoCommunity organisation (or else tell me what I should do to deserve it...) ? I would like to close many duplicated "me too" issues and organize job with projects board. There are also ready PRs waiting for merge. Thank you in advance.

**Comment by cytec** [comment]
@ymartin59 afaik only @Diaoul can add new members so i guess you'll have to wait till he finds some time again to check back here

**Comment by Safihre** [comment]
Well, has anyone tried sending him an email? It's listed on his profile. Get all of you full permissions so the project can move forward.
The whole project depending on 1 person that doesn't have enough time anymore, that doesn't sound like a good plan! 
I would be afraid this project is slowly loosing purpose if the DSM6+ support doesn't start rolling soonish.

**Comment by cytec** [comment]
i've shot him a mail ;)

**Comment by Diaoul** [comment]
Done! Sorry I missed the ping.

**Comment by Safihre** [comment]
@ymartin59 Do you still want ideas for Travis automation? Since I have been playing around with it a bit. 
I can open a separate issue about it.

**Comment by ymartin59** [comment]
@Safihre I saw your configuration file from a PR https://github.com/ymartin59/spksrc/blob/master-travis/.travis.yml I also found some scripts to process PR commits and automatically detect packages to build.
... a separate issue may be a good idea... after DSM 6 is rolled out and we can close tens of them first.

**Comment by torrentalle** [comment]
I fixed the PR #2533. The branch is merged with current `master` and build fixed
