### ISSUE TITLE
SABnzbd not starting on DSM 6.1.4

### ISSUE THREAD

**Issue by desperado591** [SynoCommunity/spksrc#2996]
Hi,

I have been running SABnzbd on my Synology NAS for years now, but after uninstalling it from Volume 2 and reinstalling it to Volume 1, it just won´t start anymore. 

I have already made the user "sabnzbd" visible and granted him admin rights. 

I also tried changing the user to root in /var/packages/sabnzbd/scripts/start-stop-status with no success.  

Next step was trying to change the etc/shadow file by changing the sabnzbd entry to sabnzbd:*:10933:0:99999:7::: 

Still I can not start SABnzbd. Everytime I try to start it just says "failed to run the package service"

Does anybody have a suggestion for me?

### Setup
_Package Name:SABnzbd_
_Package Version:2.3.0-32_

_NAS Model:DS1815+_
_NAS Architecture:_
_DSM version:6.1.4-15217 _

### Expected behavior
SABnzbd should run

### Actual behavior
failed to run the package service

**Comment by ymartin59** [comment]
Installer script does not work on DSM 6.x. I guess you installed package on DSM 5.x and upgrade your system to DSM 6.x
Support for DSM 6.x is in progress #2904

**Comment by desperado591** [comment]
Well on my DS1815 it was indeed originally installed under DSM5 and upgrated. But on my DS212+ and my DS1513+ I made complete new setups of DSM6 and installed SABnzbd afterwards. After giving admin rights to the sabnzbd user it is working on these 2 machines without any problems.

Is there any workaround until the installer is working proper again?

**Comment by ymartin59** [comment]
Fixed but not published as repository is unable to deliver DSM 6.x packages. So work is still in progress.
I propose you to try to clean up "sabnzb" service user on your DSM 6 and try to install again.

**Comment by desperado591** [comment]
What do you mean with "clean up sabnzbd service user"? Delete the user and create it new? I have done that many times without success.

I either created the sabnzbd user with admin rights before installing SABnzbd itself, or the other way around e.g. I installed SABnzbd first and made the user visible afterwards and granted him admin rights. Neither method was successfull.

**Comment by Safihre** [comment]
Maybe you can try this one? I compiled it for DSM6:
https://github.com/Safihre/spksrc/releases/tag/sabnzbd-1-dsm61
Make sure to get the right version for your system. This one of course won't automatically update.

**Comment by desperado591** [comment]
It is still not starting :-(
What user is this package using? There is a new sc-sabnzbd user in the etc/passwd file. If that is the one the package is using, I can try to make that user visible and give it admin rights.

**Comment by Safihre** [comment]
Yes that's the user you need to give permissions!

**Comment by desperado591** [comment]
OK I tried to make that user visible as I have learned in that german Synology Forum thread [http://www.synology-forum.de/showthread.html?55973-Alle-User-im-DSM-anzeigen&p=442973&viewfull=1#post442973](url) 

But as I have feared: Even that is not working, maybe because that new user has such a high UID and GID? Regarding to the mentioned how-to every user with a UID under 1024 is not shown in DSM, so one has to change the UID to a higher number like for example 1050. But the user sc-sabnzbd has already a UID of 229406 and a GID of also 229406 - but it isn´t showing up in DSM.

So I am simply not able to give that user the needed permissions :-(

Luckily I was able (with the help of the german Synology Forum) to setup SABnzbd in Docker and after some fiddling it is now running and working. Nevertheless I will be happy to help and try out the "normal" package if I get some advice how to change that damn new user ;-)

**Comment by darkeagl** [comment]
Hello, so did install the packages from @Safihre , thank you for them. But I cannot start them. I get the package service error. I already changed the passwd file with the gid and uid and gave the sc-sab.. and sc-sick the admin permission, but still no success. Do I miss anything?
Every help is appreciated
![nas_passwd](https://user-images.githubusercontent.com/18231446/33336754-2f11694a-d471-11e7-870b-391b825b1db1.jpg)
![nas_shadow](https://user-images.githubusercontent.com/18231446/33336755-2f3036c2-d471-11e7-9823-60df36ddb80c.jpg)
![nas_user](https://user-images.githubusercontent.com/18231446/33336756-2f4d7b56-d471-11e7-8829-521c02c5506e.jpg)

**Comment by tensaikashikoi** [comment]
I managed to resolve this issue by following this tutorial (in Dutch)
https://nzbusenet.com/sabnzbd-werkend-krijgen-op-dsm-6/

Basically, change the user using SSH to 'root'.

**Comment by Safihre** [comment]
Test packages for DSM6.1 and various architectures are available here #3138. They also include a new way of handling permissions.
We hope to publish the packages to the official repo soon and appreciate all testing and reports on the functioning of these packages.

**Comment by ehran** [comment]
Hello everyone,

After a reboot of my DS415+ I lost all the system partition and had to reinstall everything (thanks, Syno...) and I am having the same issue than most users of DSM 6 are now facing... all my favorite packages are not working anymore... I got Plex but no SickBeard, no Couchpotato, no SABnzbd... 

Any news on the development for DSM 6 of these ? any more or less stable version available that can be used on DS415+ or temporary fix? Ive tried the suggestion of installing without launching - restart - launch, didn't work, tried all the SSH modifications of ownership, vi edits etc... nothing... but I do have a backup of all the config files from the previous installations...

thanks in advance
Ehran

**Comment by Safihre** [comment]
Get them and install them fresh from #3138.
