### ISSUE TITLE
Deluge 1.3.15-8

### ISSUE THREAD

**Issue by bigcid10** [SynoCommunity/spksrc#3108]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_Deluge 
_Package Version:_1.3.15-8

_NAS Model:_Synplogy DS716+II
_NAS Architecture:_X86
_DSM version:_DSM 6.2 - 23511

### Expected behavior
Tell us what should happen

### Actual behavior
python got auto updated this morning to 2.7.17-17
seems to have broken deluge

### Steps to reproduce
_1._uninstalled deluge and reinstalled(no avail)
_2._uninstalled python and reinstalled (no avail)
_3._uninstalled and reinstalled both ,rebooted (no avail)

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by Bon3** [comment]
Same problem here... :(

**Comment by jrac86** [comment]
Same issue with Deluge

**Comment by SomeoneElseHasMyName** [comment]
Same issue alas

**Comment by ymartin59** [comment]
Sorry for the inconvenience.
Workaround:
- Backup /var/packages/deluge/target/var
- Uninstall deluge and python
- Install again python (old version 2.7.13-16 is now back online) and Deluge
- Stop Deluge service
- Restore backup into /var/packages/deluge/target/var
- Start Deluge service

**Comment by Futerix** [comment]
Solved by this metod.

**Comment by Safihre** [comment]
I recompiled Python 2.7.14 package but now with the correct `start-stop-deamon` and hopefully a fix for other crashes related to `cryptography`. [Would you like to give it a try?](https://github.com/Safihre/spksrc/releases/tag/python-recompile3)

Now that we also got your attention, we have new packages that we are testing for [NZBGet, SABnzbd, CouchPotato, Sickrage, SickBeard Custom, Syncthing, Mono, Jackett, Tvheaded, Sonarr and Radarr](https://github.com/SynoCommunity/spksrc/issues/2945#issuecomment-357008518).
Would you be willing to try those? If you have Python 2.7.13 or 2.7.14, we want to know if they work in all cases. Let us know if you test 👍 Others tested these packages already, but more testing is better clearly!
Thank you! 🥇

**Comment by Futerix** [comment]
I can confirm that yesterday when i was in the same situation the only program that did not start (tryed all the metod and no luck) was only deluge... the other apps that i have installed like plex, sonar, radarr, transmission, jacket, mono etc all of them worked like a charm.
The fix was to downgrade python.
I have limited time and i canot help you with future test.

**Comment by MattyJasper** [comment]
@Safihre I have downloaded your updated Python package on to my DS3615xs and rebooted but it has sadly not fixed the issue with Deluge. Any suggestions?

**Comment by ymartin59** [comment]
Fix is identified in `setup-service.sh` script... It is required to rebuilt and publish all python packages. I should find time slot to do so until tomorrow night.
Work-around is to uninstall application (with a backup of their specific `var` folder) and python, then to reinstall with current versions online.

**Comment by Safihre** [comment]
@ymartin59 no that only fixes the problem for some packages.. It seems there is something specifically wrong with Python that breaks Deluge.  In the other thread someone posted a Traceback with a failure in Cryptography.
The link I shared above here is already recompiled with the correct `start-stop-deamon` but as @MattyJasper describes, it still doesn't work.
I will try to dive into this as soon as my internet is back.

**Comment by ymartin59** [comment]
@Safihre OK let me know, thanks to a new PR. I let this publication pending... Probably Deluge package has to be updated itself too. Question: does Deluge now run on Python 3 or still stuck to Python 2 ?

**Comment by MattyJasper** [comment]
@ymartin59 I have tried backing up the var directory for Deluge but I did not have permissions to copy 3 files; auth, and the two files in the ssl directory daemon.cert and daemon.pkey. I don't mind having Deluge down for a while if it helps @Safihre with testing the Python release. Unfortunately (or fortunately) Deluge is the only Python dependent package I have installed.

**Comment by m4tt075** [comment]
@MattyJasper When you `ssh` into your DSM6.1 system as `admin` (which is correct), you do not have full `root` permissions. After you have logged in, enter `sudo su -` and then the `admin` password again and you can copy everything.

**Comment by ymartin59** [comment]
Here is an easier way to downgrade python version without uninstalling applications:
- download package from https://packages.synocommunity.com/python/16/python.v16.f4458%5Bx86-braswell-bromolow-cedarview-avoton%5D.spk
- use Package Center "manual install" to downgrade version

Hope this helps

**Comment by MattyJasper** [comment]
@ymartin59 Nice idea unfortunately it doesn't work! Synology Package Manager gives an error; "Current package version is 2.7.14-17. You cannot downgrade it to the older version 2.7.13-16."

@m4tt075 Thanks for the heads up, I may have to give that a go :)

**Comment by emulienfou** [comment]
Hi there, where can I find an **x64** version of **Python 2.7.13-16** for my DS418play?

Thanks

**Comment by ymartin59** [comment]
It does not exist, never build for `apollolake`. We will have to wait for python-2.7.14 packaging, after trouble is fixed.

**Comment by Safihre** [comment]
@emulienfou The 2.7.14 version in #3138 works perfect for `x86` systems and does not have the problems described by some here.

**Comment by emulienfou** [comment]
@Safihre thank for the answer but the issue in the `x64` system is I don't have the `start-stop-daemon` command.

**Comment by Safihre** [comment]
Again, like I wrote above, the Python package listed in #3138 *does* include the start-stop-deamon.

**Comment by emulienfou** [comment]
@Safihre Yes, I install your package [python_x64-6.1_2.7.14-17.spk](https://github.com/Safihre/spksrc/releases/tag/python-dsm61-new-all) but command `start-stop-deamon` still doesn't exists!

**Comment by Safihre** [comment]
The command is not installed as a system-wide command but only in the Python-path, which the other packages are setup to include automatically. It's definitely there.

**Comment by emulienfou** [comment]
Hello @Safihre, just install the last compiled build released by yourself 5 hours ago.
However, I still don't have the `start-stop-daemon` command available.
I restart my Synology in case off, and when I do a `which start-stop-daemon` it didn't find the command even I'm logged as root or not!

**Comment by emulienfou** [comment]
After searching on deluge site, we are using the [Ubuntu Init Script](http://dev.deluge-torrent.org/wiki/UserGuide/Service/DebianUbuntuInitd) but it's seems to be `DEPRECATED`.

Why don't using the [FreeBSD Init Script](http://dev.deluge-torrent.org/wiki/UserGuide/Service/FreeBSD) instead like **Transmission** package do?

**Comment by Safihre** [comment]
@emulienfou The build for the `x64` never finished because halfway through building, the source website for one of the dependencies went down. So it was still the old Python. 
Restarted build now: https://travis-ci.org/Safihre/spksrc/jobs/342259827
This one (after building completes) really will have the `start-stop-daemon` in there, trust me this time 😉

**Comment by Safihre** [comment]
Oh how embarrassing, it seems I make another typo 👎 
I corrected the typo and started another build: https://travis-ci.org/Safihre/spksrc/builds/342491793

The other script could indeed be a replacement for `start-stop-daemon`, if all commands are available on all platforms and DSM versions. What do you think @ymartin59?

**Comment by Safihre** [comment]
@emulienfou Could you try it again with the new version on https://github.com/Safihre/spksrc/releases/tag/deluge-dsm61-all with the newly compiled  https://github.com/Safihre/spksrc/releases/tag/python-dsm61-new-all ?

**Comment by emulienfou** [comment]
Hello @Safihre finally, it's a win :smile: this 2 packages works perfectly and Deluge has started successfully. Thank you

**Comment by Safihre** [comment]
Package converted for DSM6 support. Get it in #3138 and give us feedback there if it doesn't work.
After it's final release it will auto-update again via the official SynoCommunity repository.
