### ISSUE TITLE
Synology / Deluge not starting afte python update to 2.7.14-17

### ISSUE THREAD

**Issue by Rabbyapo** [SynoCommunity/spksrc#3109]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:Deluge
_Package Version:1.3.15-8

_NAS Model:DS3615xs
_NAS Architecture:_
_DSM version:6.1.4-15217 Update 5

### Expected behavior
start deluge after updating python

### Actual behavior
deluge is not starting

### Steps to reproduce
_1._update python package to 2.7.14-17
_2._start deluge

#### Package log
tried to reinstall deluge package -> empty log

**Comment by Futerix** [comment]
Same here, uninstalled phyton, deluge and chroot and reinstalled but the problem persist.
Absolut zero problem for the latest 30days 24/7 till today upgraded to the latest pyton that mess with the deluge.

I think il go for docker, much safer than this.

**Comment by jrac86** [comment]
Same exact issue. Tried reinstalling and still will not start. No data in log either.

**Comment by Futerix** [comment]
I think the pyton has screwed something.
No log either forgot to mention.

**Comment by BoKKeR** [comment]
No log either. same on my machine. There is no good way to debug the Synology packages as far I know.

**Comment by Bon3** [comment]
Hope someone finds a fix soon :)

**Comment by SliceOfSublime** [comment]
Same problem . . . I agree with a comment in another thread with a request to release the prior .spk until this is fixed.

**Comment by SWu** [comment]
Looks like the Deluge startup script relied on the start-stop-daemon executable being available on the path, which was likely removed from the latest python package. I fixed it by sshing into my NAS and copying it from another package, e.g. `sudo cp /usr/local/sonarr/bin/start-stop-daemon /usr/local/deluge/bin/ && sudo chown deluge /usr/local/deluge/bin/start-stop-daemon`

**Comment by SWu** [comment]
I believe the fix is to add cross/busybox which provides the start-stop-daemon executable to the list of DEPENDS for deluge: https://github.com/SynoCommunity/spksrc/blob/master/spk/deluge/Makefile#L9

**Comment by SomeoneElseHasMyName** [comment]
same issue - hoping for a quick resolution

**Comment by SliceOfSublime** [comment]
@SWu I copied a start-stop-daemon from sonarr. Deluge still won't run, however, I no longer get the fail to start error message and now get a log . . . thoughts?
<img width="965" alt="deluge log" src="https://user-images.githubusercontent.com/35509840/35023909-171e27c4-fafa-11e7-9fa4-3581911991b0.png">

**Comment by csgnyc** [comment]
@SliceOfSublime  I followed SWu's steps (although I used Radarr to source my start-stop-daemon), and then restarted  the Synology.  Before I restarted, nothing happened, but after restart it seems to be up and running again.

**Comment by brandonscript** [comment]
Yep, not the greatest workaround, but in `start-stop-status`, I edited the user from `deluge` to be `root`, and then copied:

    sudo cp /volume1/\@appstore/nzbdrone/bin/start-stop-daemon /usr/local/deluge/bin/
    sudo chown root /usr/local/deluge/bin/start-stop-daemon

Super insecure, but it works. Hopefully a proper fix will find its way down the pipe and we can reinstall the proper package.

**Comment by ymartin59** [comment]
Please try workaround described at https://github.com/SynoCommunity/spksrc/issues/3108#issuecomment-358270497

**Comment by BoKKeR** [comment]
I am not sure if its connectable with the python issue but after deluge uninstall I ended up with a deluge appearing in the package manager as installed but I cant run the only option is uninstall. which fails with:

Failed to uninstall package.

here is the same from synopkg with no error at all.

`ash-4.3# synopkg status deluge-1.3.15-8
No such package deluge-1.3.15-8
Status: [255]
ash-4.3# synopkg uninstall deluge-1.3.15-8
ash-4.3#
`
but it appears on the list. In the package center, it states: Deluge Not available.

**Comment by Futerix** [comment]
@ymartin59 - that done the trick. thx worked.

**Comment by TheFuben** [comment]
same here. unfortunately without ssh access atm, a update would therefore really be appreciated, thx!

**Comment by Safihre** [comment]
@SliceOfSublime what type of Synology do you have?

**Comment by foal** [comment]
Same issue.
My workaround: uninstall deluge, uninstall python, install deluge. While deluge installation, if install the 2.7.13-16 python automatically. Disable python update after that.

**Comment by BoKKeR** [comment]
@foal No. the new python got removed that caused deluge to malfunction. you are safe to have the updates on.

**Comment by Nottt** [comment]
I use docker, I just stopped my container and started again...I really have no idea how my docker updated it... what do you suggest to make future docker stick to this specific release?

**Comment by ymartin59** [comment]
There is no python version 2.7.13-16 for `dockerx64` architecture.

**Comment by wzzly** [comment]
There is also no python version 2.7.13-16 for evansport architecture that I need

**Comment by ymartin59** [comment]
@wzzly Yes there is: https://packages.synocommunity.com/python/16/python.v16.f4458%5Bx86-braswell-bromolow-cedarview-avoton%5D.spk

**Comment by wzzly** [comment]
@ymartin59 no that one is not for DS214play evansport.. I tried it

**Comment by ymartin59** [comment]
@wzzly Sorry I made a mistake in my copy/paste. Here it is: https://packages.synocommunity.com/python/16/python.v16.f4458%5Bevansport%5D.spk

**Comment by wzzly** [comment]
I installed python 16.3 and want to install deluge... but the deluge installer says it need to update python to install...? How did you guys make this work?

**Comment by emulienfou** [comment]
Hi,
here are some investigation and test I perform on my Synology.
Hope this will help someone to fix this issue.

I build and install **Python 2.7.14-17** and **Deluge 1.3.15-8** on my DS418play on Arch x64.

1. I try to run deluge service from *Package Center* and get the message like you: `Failed to run the package service`.

2. I try to run the deluge service has root from command line using: **synoservice --enable pkgctl-deluge** and get the next message: `service [pkgctl-deluge] start failed, synoerr=[0x0000]`.

3. I found that logs are stored in: `/var/log/synopkg.log` file and get the next logs:
```logs
2018/02/14 23:33:36	stop deluge 1.3.15-8 Begin pre-load apparmor
2018/02/14 23:33:36	stop deluge 1.3.15-8 End pre-load apparmor ret=[0]
2018/02/14 23:33:36	stop deluge 1.3.15-8 Begin start-stop-status start
/var/packages/deluge/scripts/start-stop-status: line 50: start-stop-daemon: command not found
/var/packages/deluge/scripts/start-stop-status: line 52: start-stop-daemon: command not found
Starting Deluge ...
/var/packages/deluge/scripts/start-stop-status: line 29: start-stop-daemon: command not found
/var/packages/deluge/scripts/start-stop-status: line 32: start-stop-daemon: command not found
2018/02/14 23:33:39	stop deluge 1.3.15-8 End start-stop-status start ret=[127]
2018/02/14 23:33:39	(system) trigger deluge 1.3.15-8 Begin start-stop-status stop
/var/packages/deluge/scripts/start-stop-status: line 50: start-stop-daemon: command not found
/var/packages/deluge/scripts/start-stop-status: line 52: start-stop-daemon: command not found
Deluge is not running
2018/02/14 23:33:39	(system) trigger deluge 1.3.15-8 End start-stop-status stop ret=[0]
2018/02/14 23:33:39	(system) trigger deluge 1.3.15-8 Begin unload apparmor
2018/02/14 23:33:39	(system) trigger deluge 1.3.15-8 End unload apparmor ret=[0]
```

4. I also found that deluge daemon and web-ui are working correctly. You can run them by executing the next commands:
```bash
cd /usr/local/deluge/env/bin/
./deluged
./deluge-web
```
> You will be able to access to the Deluge Web-UI in the port **8112**.

Hope this can help someone finds the issue!

**Comment by Safihre** [comment]
Closing this, the new Python package should fix these problems.
If you still experience problems after the 2.7.14-18 update, please create a new issue.
