### ISSUE TITLE
Permissions gone since Sonarr/Transmission update

### ISSUE THREAD

**Issue by WolfH** [SynoCommunity/spksrc#3192]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Sonarr / Transmission
_Package Version:_ Latest update

_NAS Model:_ DS214
_NAS Architecture:_ ARM
_DSM version:_ DSM 6.1.5-15254 Update 1

### Expected behavior
Sonarr should be able to move items from the Transmission download-folder to the media-folder as it did before the update.

### Actual behavior
It seems that permissions for Sonarr have been set wrong since updating to the newest version using the sc-download group. I'm getting errors like:

`Couldn't import episode /volume1/homes/admin/downloads/NAME.mkv: Access to the path is denied.`

I've checked the permissions in File Station and the downloads folder is owned by user sc-transmission and group sc-download (to which sonarr belongs if I'm not mistaken).

It worked fine before, this all started since updating to the new permissions-structure.

### Steps to reproduce
_1._ Install the latest update.
_2._ Try to download and move a file.

**Comment by Safihre** [comment]
How are you with SSH? We need to identify where this is going wrong. Maybe you can also help @SX86?
If you SSH into the device, can you post the output of each folder in the path up to the file of:
```
ls -al /volume1/
sudo synoacltool -get "/volume1/" 
```
And then also for any of the folders up to the file's folder?

**Comment by WolfH** [comment]
I'm not super with SSH, but here goes nothing. I mentioned the wrong folder above, it's the bittorrent folder.

```
admin@TheTARDIS:~$ ls -al /volume1
total 10956
drwxr-xr-x  16 root  root       4096 Feb 28 08:26 .
drwxr-xr-x  21 root  root       4096 Feb 28 08:26 ..
drwxr-xr-x  19 root  root       4096 Mar  2 07:59 @appstore
-rw-------   1 root  root      14336 Feb  6 08:17 aquota.group
-rw-------   1 root  root      15360 Feb  6 08:17 aquota.user
drwx------   2 root  root       4096 Feb  6 08:12 @autoupdate
drwxr-xr-x   5 admin users      4096 Feb 27  2017 @database
drwxr-xr-x   2 admin users      4096 Oct 14  2013 @download
drwxrwxrwx+  4 root  users      4096 May 12  2015 @eaDir
-rw-------   1 root  root   10395648 Jun 14  2014 @heartbeatd.core
drwxrwxrwx+  8 root  root       4096 Apr 27  2016 homes
drwx------   3 root  root       4096 May  2  2017 @iSCSI
drwx------   2 root  root      16384 Oct 14  2013 lost+found
-rw-------   1 root  root     258048 Jan  8  2017 @mono.core
-rw-r--r--   1 root  root       2048 Nov 21  2013 .quarantine
drwxr-xr-x   3 root  root       4096 Nov 21  2013 @quarantine
drwxr-xr-x   2 root  root       4096 Nov  7  2014 @S2S
drwxrwxrwx   4 root  root       4096 Sep 10  2014 @spool
-rw-------   1 root  root  138031104 Jul  8  2017 @synoelasticd.core
-rw-------   1 root  root   11952128 Jan  8  2017 @synopkg.core
-rw-------   1 root  root       5120 Mar 23  2016 synoquota.db
drwxrwxrwx   5 root  root       4096 Mar  2 08:56 Backups
drwxrwxrwt  14 root  root       4096 Mar  2 08:57 @tmp
drwxr-xr-x   4 root  root       4096 Feb 27  2017 @USBCopy
-rw-r--r--   1 root  root      28672 Jun  7  2015 winbindd_cache.tdb
```
```
admin@TheTARDIS:~$ sudo synoacltool -get "/volume1/" `
(synoacltool.c, 359)It's Linux mode
```
```
admin@TheTARDIS:~$ ls -al /volume1/homes
total 76
drwxrwxrwx+  8 root             root  4096 Apr 27  2016 .
drwxr-xr-x  16 root             root  4096 Feb 28 08:26 ..
drwxrwxrwx+  8 admin            users 4096 Feb 28 22:09 admin
-rw-rw-rw-   1 admin            users  291 Oct 24  2013 .apdisk
-rw-rw-rw-   1 admin            users 6148 Jul  7  2016 .DS_Store
drwxrwxrwx+  3 root             users 4096 Feb  6 08:19 @eaDir
drwxr-xr-x   6 User1 users 4096 Sep 20 12:58 User1
drwxrwxrwx+  2 root             root  4096 Aug 11  2015 #recycle
drwxrwsrwt   4 admin            users 4096 Jul 15  2014 .TemporaryItems
drwxr-xr-x   2 backups      users 4096 Apr 27  2016 backups
```
```
admin@TheTARDIS:~$ sudo synoacltool -get "/volume1/homes/" 
ACL version: 1 
Archive: has_ACL,is_support_ACL 
Owner: [root(user)] 
--------------------- 
	 [0] group:administrators:allow:rwxpdDaARWc--:fd--  (level:0)
	 [1] group:sc-download:allow:--x----------:---n  (level:0)
```
```
admin@TheTARDIS:~$ ls -al /volume1/homes/admin/
total 1056
drwxrwxrwx+ 8 admin           users         4096 Feb 28 22:09 .
drwxrwxrwx+ 8 root            root          4096 Apr 27  2016 ..
-rw-rw-rw-  1 admin           users          290 Oct 22  2013 .apdisk
drwxrwx---  7 sc-transmission sc-download  36864 Mar  2 08:29 bittorrent
drwxrwx---  6 admin           sc-download   4096 Nov  3  2013 downloads
-rw-rw-rw-  1 admin           users         6148 Dec 27 22:44 .DS_Store
drwxrwxrwx+ 2 root            users         4096 Feb 28 22:09 @eaDir
drwxrwsrwx  7 admin           users         4096 May  6  2017 iTunes
drwxrwxrwx  6 admin           sc-download   4096 Apr 14  2015 Media
drwxrwxrwx  3 root            root          4096 Mar 26  2016 Reports
-rw-------  1 admin           users         1379 Dec 27 21:07 .viminfo
-rw-rw-rw-  1 admin           users       951739 Oct 27  2013 .VolumeIcon.icns
```
```
admin@TheTARDIS:~$ sudo synoacltool -get "/volume1/homes/admin/" 
ACL version: 1 
Archive: has_ACL,is_support_ACL 
Owner: [admin(user)] 
--------------------- 
	 [0] group:administrators:allow:rwxpdDaARWc--:fd--  (level:0)
	 [1] group:sc-download:allow:--x----------:---n  (level:0)
```
```
admin@TheTARDIS:~$ ls -al /volume1/homes/admin/bittorrent/
total 14715760
drwxrwx---  7 admin           sc-download       36864 Mar  2 08:29 .
drwxrwxrwx+ 8 admin           users              4096 Feb 28 22:09 ..
-rwxrwxrwx  1 admin           sc-download        6148 Aug 27  2017 .DS_Store
drwxrwxrwx+ 2 sc-transmission transmission      12288 Mar  2 08:19 @eaDir
and a whole list of files
```
```
admin@TheTARDIS:~$ sudo synoacltool -get "/volume1/homes/admin/bittorrent/" 
(synoacltool.c, 359)It's Linux mode
```

**Comment by Safihre** [comment]
Could you try once more to set/add `sc-download` to `/volume1/homes/admin/bittorent`? Seems  something set Linux permissions on that folder and the files in there are owned by `transmission`.

**Comment by elisimpson** [comment]
After uninstalling old version and installing new Transmission I'm seeing the user set to "sc-transmission" and group to "transmission"... is this right? I thought the group was supposed to set to "sc-download"

**Comment by Safihre** [comment]
The `sc-transmission` is a member of `sc-download ` so they share the same access.

**Comment by SX86** [comment]
@Safihre I can help, for sure! Not sure how posting the listing of volume1 will help though, so I will only post what matters to me in this case, the `download` folder.

Like @elisimpson  said, I was expecting the new downloads from Transmissions to be owned by user:group `sc-transmission:sc-download` and not `sc-transmission:transmission`.

Here's some of the info you requested:
```
ash-4.3# sudo synoacltool -get "/volume1/"
(synoacltool.c, 359)It's Linux mode
```
```
ash-4.3# sudo synoacltool -get "/volume1/download"
ACL version: 1
Archive: has_ACL,is_support_ACL
Owner: [root(user)]
---------------------
         [0] group:administrators:allow:rwxpdDaARWc--:fd--  (level:0)
         [1] group:sc-download:allow:--x----------:---n  (level:0)
```
```
ash-4.3# ls -al /volume1/download/
total 40
d---------+  7 root            root         4096 Mar  2 10:15 .
drwxr-xr-x  29 root            root         4096 Feb 27 10:15 ..
drwxrwxrwx   7 sc-transmission sc-download  4096 Mar  1 10:09 Downloads
drwxrwxrwx+  3 root            root         4096 Feb 19 16:46 @eaDir
drwxrwxrwx   2 sc-transmission sc-download 12288 Mar  2 04:45 Incomplete
-rwxrwxrwx   1 Franck          users           0 Dec 10  2015 .nomedia
-rwxrwxrwx   1 Franck          users        2325 Dec 17 20:22 SonarrCleanUpScript.ps1
drwxrwxrwx   4 sc-transmission sc-download  4096 Mar  1 10:03 Torrents
drwxrwxrwx   3 Franck          users        4096 Nov 16  2016 Transmission Remote GUI Settings
```
"Downloads" is my default download location for Transmission. I manually set the permissions on it yesterday. But, here's the attributes of a folder that was created by Transmission from a downloaded torrent:
```
drwxrwxrwx   2 sc-transmission transmission       4096 Mar  1 23:07 FolderName
```
and it's content (I trimed some of it, there was about 30 files with the same permissions in there, but kept 2 to demonstrate):
```
ash-4.3# ls -la
total 1885788
drwxrwxrwx   2 sc-transmission transmission      4096 Mar  1 23:07 .
drwxrwxrwx 266 sc-transmission sc-download      36864 Mar  2 04:45 ..
-rw-rw-rw-   1 sc-transmission transmission     10889 Mar  1 23:05 FileName.nfo
-rw-rw-rw-   1 sc-transmission transmission  50000000 Mar  1 23:07 FileName.rar
```

**Comment by elisimpson** [comment]
Yep I'm seeing same as @SX86 ... with the additional note that the dirs and files for transmission under @appstore are also all sc-transmission:transmission. As far as I can see sc-download isn't being set anywhere (as a user or group).

**Comment by Safihre** [comment]
Repeating it again: `sc-transmission` is part of `sc-download`.
The problem here is different, it's the problem of mixing Synology and Linux permissions that I still have to investigate.

**Comment by elisimpson** [comment]
Maybe it's because the old transmission user ID was 100, same as the group ID for "users"?

more /etc/passwd
...
transmission:x:100:100:Transmission User:/usr/local/transmission/var:/bin/sh


The question I have is all the group owners being set to "transmission" an issue we should be concerned about? If it's no big deal, I'll move forward, but if it's supposed to be "sc-download" I'd rather not have to fix ownership later on potentially 1000s of files if I can avoid it.

**Comment by WolfH** [comment]
> Could you try once more to set/add sc-download to /volume1/homes/admin/bittorent? Seems something set Linux permissions on that folder and the files in there are owned by transmission.

I've set group permissions for the bittorrent folder and everything inside to sc-download, restarted the NAS but am still running into the same issue... :(

**Comment by tweakert** [comment]
Exactly the same problem here. After updating Sonarr to latest version, it's not possible anymore for Sonarr to move files from Sabnzb download folder to the Sonarr folder (access denied).

**Comment by JonasL1** [comment]
SickRage permissions are also gone after the update of Transmission.

**Comment by elisimpson** [comment]
One other additional tidbit of info: the "sc-transmission" user and "transmission" group have the same ID: 190144. Maybe that's why it's is setting the group to "transmission" instead of "sc-download"?

**Comment by ymartin59** [comment]
@elisimpson "sc-transmission" is created by DSM 6 package framework, and as a user requires a default group, it creates "transmission" with same ID. So no worry about it. "sc-transmission" is member of group "sc-download" even if you do not see that technical user in DSM user/group management (as explained and detailed in package upgrade wizard, you probably have not read !)

**Comment by ymartin59** [comment]
Please open DSM user/group management interface and try to add user "sonarr" (or "radarr") as "sc-download" group member. If I guessed right, it should fix your permission denied troubles. Please report feedback. CC @Safihre

**Comment by SX86** [comment]
@ymartin59 that can't be done from the DSM group management. sonarr is not listed as a user in DSM.
I was able to solve the issue partially by changing the umask setting in Transmission's "settings.json".
I just find it strange that Transmission is now setting the group for downloaded files as "transmission" instead of "users", or "sc-download".

**Comment by Safihre** [comment]
What did you set now for umask setting and what has changed after that in how it writes the files? Maybe that could be the solution!
The group is set by DSM when running the package, it's the same the package name. This is how Synology says we should do it but SynoCommunity just ignored that before (if I understand correctly).

**Comment by ymartin59** [comment]
@SX86 I guess your download "share" folder was pre-existing to upgrade. I am interested to know if manually granting "sc-download" group to that "share" folder from DSM File Manager would fix your trouble.

**Comment by ymartin59** [comment]
@WolfH I wonder if your trouble may come from your specific download location (a directory in home folder): `/volume1/homes/admin/downloads`. Packages have been designed and tested to write in DSM "share" folder.

**Comment by WolfH** [comment]
I just saw the latest update for the Sonarr and Radarr packages. Installed them and now everything is working again! Don't know what was fixed exactly, but all's well that ends well!

**Comment by Safihre** [comment]
Really? Cool!

**Comment by elisimpson** [comment]
Is there any reason why we shouldn't readd sc-transmission to the users group? Seems like kind of an arbitrary choice to remove it that causes a lot of permissions issues with legacy files/folders.

**Comment by Safihre** [comment]
@ymartin59 @BenjV what do you guys think?
At this point I kind of agree, we would resolve all this problems if we use the `syno_user_add_to_legacy_group` function. So that it only gets added if the old package user was part of `users`. Because for fresh installs the `sc-download` way does work, it's the old files causing the problems. And also that some packages already use `sc-download` (Sonarr/Radarr), while others do not yet (sabnzbd/nzbget)..

**Comment by BenjV** [comment]
Please don't add this sc- groups to the users group.
That will kill the whole purpose of running packages with less privileges.
Every account on DSM is a member of the group users, so you cannot protect files/folder from any user.

I know that was the case in the past, but this was the major reason why everything had to change.
Don't keep this very faulty situatie alive for the sake of compatibility.

**Comment by ymartin59** [comment]
My point of view is to instruct users how to fix permissions in File Manager thanks to a proper wiki page. Applying `sc-download` permissions to existing folders/files is not so a complex task (and automate it in package installer is not an option - may be too long/slow)

**Comment by elisimpson** [comment]
Fair point about why we shouldn't make the change. The problem is there's really no explanation or guidance from Synology about why that change was made and how to adapt legacy systems to the new rules. I'm sure they don't want to scare users with a bunch of tasks to do, but just leaving us in the dark is bad. 99.9% of the files on my server on owned with a group set to "users"

**Comment by tweakert** [comment]
I uninstalled everything and did a reinstall. And did a new setup.
Got the following error trying to update GUI from Sonarr: Error occurred while executing task ApplicationUpdate: Access to the path "/tmp/nzbdrone_update/NzbDrone/UI/Content/FontAwesome/FontAwesome.otf" is denied.
And also the download folder is denied.

**Comment by Safihre** [comment]
@tweakert restart your NAS first before trying to update Sonarr.

@BenjV / @ymartin59 I agree fully, but from posts here it seems it's not always working. If you scroll a little up you see these 2 users posting the ownership info of their whole path and even though it has the right groups and users, they still have problems. How could that be?

@elisimpson during the update it was shown in bold and red text that you should do this applying of permissions via File Station. What more can we do? Make it blink?

**Comment by BenjV** [comment]
I think it is a Sonarr issue.
In the service file of Sonarr you can set the permissions (user and group) for the downloaded files and most likely that override de default permissions that should be inherited from the folder and so loose the group permissions of sc-download.

**Comment by ymartin59** [comment]
@BenjV Not sure if it is Sonarr fault, but it may help to configure it properly to avoid troubles.
Here is a Sonarr screenshot with "Advanced Settings" enabled for file "Permissions".
![image](https://user-images.githubusercontent.com/2196184/36949618-21c622b0-1feb-11e8-8bcc-1887991b394f.png)

**Comment by BenjV** [comment]
Correct and that information ends up in the service file of Sonarr.
If someone enter something in the chown fields for user or group then the file permissions will change.
The group should be empty or else sc-media/sc-download

**Comment by Safihre** [comment]
Why blame Sonarr? I would say Transmission, especially cause here a user says that changing the umask settings within Transmission fixes things: https://github.com/SynoCommunity/spksrc/issues/3192#issuecomment-370195052

And it should also be noted that the SynoCommunity package specifically forces a umask setting: https://github.com/SynoCommunity/spksrc/blob/master/spk/transmission/src/settings.json
Not completely sure what that setting does, but it might explain the behavior we see that's so Transmission specific.

**Comment by ymartin59** [comment]
@Safihre Sounds right... So there is no reason to postpone Deluge publishing ?

**Comment by ymartin59** [comment]
I have installed and setup Transmission to use `/volume3/downloads/transmission/` subfolders and Linux permissions have been discarded on `/volume3/downloads` for my "regular" user over ssh:
```
yma@DiskStation:~$ ls -la /volume3/
d---------+   4 root            users            4096 Mar  4 23:06 downloads
```
To fix that situation, I added back permissions to group `users` in File Station.
I just wonder what part of package scripts may have such impact, as none triggers `users` group permission remove - except if `synoacltool -add` do not really "just add" requested permission.

**Comment by SX86** [comment]
@Safihre My umask setting is now set to "0" in settings.json. umask 0 is supposed to set 777 (rwxrwxrwx) on every files and folders Transmission creates. In my case, it only sets the permissions to 666 (rw-rw-rw-). I think this may be caused by the fact that Transmission can't set the execute permission since it is not the owner (as a group and user) of the folder it creates the download files and folders in. I think (I would have to confirm) that if I want to use the setting in Sonarr that changes the date stamp of the files to match the Air Date, it needs execute permission on the file.

However, even if the permissions are 666 on the files, it allowed Sonarr to import the file to the configured TV show's folder. I want it to be 777 for Sonarr to be able to set the date stamp on the file, but at least, now it works.

**Comment by 6uillaume** [comment]
Hello, 
I have a similar issue after updating to the last version of Transmission. Only the admin account can access the /volume1/downloads folder. Transmission seems to be unable to reach the files. I was not able to find a way to give to the users the right to access the downloads folder. 
I tried to reboot the syno, uninstall/reinstall the package without success. 
My files and folders are attached to the group transmission that doesn't exist in the Control Panel (sc-download exists) so I attached the files to sc-download and add member my users in this group. But it doesn't work.

**Comment by BenjV** [comment]
To be able to set the date stamp has nothing to do with 777.
The last bit is the execution bit and is only usefull for files that can be executed.

The normal umask should be set to 002, that will allow read and write access to files and folder from users who are in the same group.
This is the DSM default.
Don't mess with umask, especialy if you don't understand what it does.
umask is system wide setting so you will mess up the whole security system if you do this.

What you need to do is be sure the folder and all the subfolders and files have been granted read/write access for the groups sc-media and sc-download.
You have to do this with FileStation.
Got to the top folder, choose properties and grant permission to that folder en set it to do it recusively.

In alle applications like Transmission and radar be sure not to set the group to something else because the change is there that the do it with a "chown" command which put the file exclusively in one group.
Then when an application creates a file or folder it inherit the privileged settings from the folder above that you just granted read/write privs for sc-media and sc-download.

**Comment by ymartin59** [comment]
@Safihre I wonder if last `chown ${EFF_USER}` may have side-effect to discard any ACL settings on folders... So question: is `chown` is really needed, and if so probably it should be moved first. Just ideas, I have not tested yet to confirm.

**Comment by Safihre** [comment]
@ymartin59 Which `chown` do you mean? In generic service or in the package?

**Comment by BenjV** [comment]
@tweakert 
You right you are not very good at this.
The new packages are running as a User that is hidden, so they are not seen by the DSM management interface.

Users can be a member of multiple groups and the hidden Users of new packages are members of the groups sc-media and sc-download (don't ask why there are two groups, I could not tell you that).
So all those Users can access all files owned by one of those groups as long as the files have read/write privs for groups.

Normally applications just write a file to a folder and then the file will get the same owner as the folder it writing to, that's why it is important to create a top folder wich is owned by one of those two groups.

Some applications will set itself as the owner, but that owner is member of the sc-media and sc-download groups, so any User that is a member of one of those groups has access to those files.

Except some package that does not do that and set something else (via a chown command), but those can mostly be configured to do the normal thing.

@ymartin59 
Is it to late to get rid of the sc-download, because two groups are just confusing and don't add anything because all package have to be in both groups.

**Comment by dan2kx** [comment]
I'm having the same issue too, any steps to resolve the permission issue?

**Comment by BenjV** [comment]
I think you are on the right track.
I have an older NAS (DS414) and there I have a mixture of shares with and without "Windows ACL" where al the share without stem from the DSM 5 time
I have a newer test NAS from after DSM6 and there all the shares are with "windows ACL".

It seems logical that using ACL privs for the new packages will only work for shares created with ACL privs.
If that's the case none of the package will function correctly under DSM 5 and under DSM 6 all old shares have to be converted to using 'Windows ACL".

**Comment by dan2kx** [comment]
Mine too are old shares i'll try and convert to ACL...

**Comment by dan2kx** [comment]
That didn't seem to work either

**Comment by Kilay** [comment]
I had the same permission errors in Transmission and Sickbeard Custom (Medusa fork) and after converting my shared folder to "Windows ACL" and checking that sc-media and sc-download had the right permission, it is working great.

Thank you @BenjV

**Comment by Safihre** [comment]
Hmmm, now I wonder if there's a way to do this on the command-line so we can do it during upgrades!

**Comment by BenjV** [comment]
No that's not possible, because it has to be done on a share level and the package does not know which share they will be using.

The better question is whether the decision to use "windows ACL" instead of the linux privilege setting was the correct one.
If we stay with the ACL's then the only thing we could do is give the advise to convert all shares to "windows ACL" before installing the new packages.

**Comment by smoker1000** [comment]
Why should users who were using the default default setting in DSM have to convert to ACL, when it was working fine before. I appreciate the work being done but, this should have been tested before release.

**Comment by dan2kx** [comment]
@BenjV Converting the share to ACL didn't work for me...

**Comment by Safihre** [comment]
@smoker1000 we have tested for months, it didn't come up.
@BenjV Yes Linux permissions would be easier, and now with all packages part of `sc-download` is it really different than the old situation where all packages were part of `users`? I am starting to doubt the whole approach now since it only adds complexity.

**Comment by smoker1000** [comment]
I guess the update in my case, didn't complete for some reason and left wierd settings.
Originally my TV shows folder was set as Owner-Admin, Groups-Users and all my individual tv shows folders within the folder Tv Shows had permissions of Owner-sc-nzbdrone and Group-nzbdrone

After the update the TV Shows folder stayed the same, Owner-Admin, Groups-Users and the individual tv shows forlders were 95% changed to Owner-101 and Group-Users

Have no idea where the Owner-101 is coming from.

Also when a new show is added to Sonarr and it creates a new folder for the show it is created as Owner-sc-nzbdrone and Group-nzbdrone

I had tried to set the video folder as Owner-Admin and Group as both sc-media and sc-download and neither would let sonarr move the files

And now there is no way to have the package try to install again to see it it changes anything

**Comment by SX86** [comment]
@smoker1000 Uninstalling and re-installing won't change the permissions on your download and import folders. That's something you need to do yourself. Be sure to also apply the Read/Write permission recursively to all sub folders and files of you download and import folders.

Owner/User 101 is most likely the User ID of the user previously called "nzbdrone", which has now been deleted, and a new one has been created; sc-nzbdrone. The new user has most likely picked up a new UID, which needs to be used on the folders were user 101 is the owner.

**Comment by SX86** [comment]
I decided to bite the bullet, take one for the team, and convert my `download` and `video` shares to Windows ACL. For each, I gave full read/write access to the share and all of its files and subfolders to the groups `sc-media` and `sc-download`. Sonarr then proceeded to pickup some newly aired episodes, sent them to Transmission for download, Sonarr then imported the file from the `download` share to the `video` share, and voilà! Everything works like it should again! No more errors in the logs, no more warning, everything works!

What I am understanding from this is that SynoCommunity is upgrading it's packages to follow the new way permissions should be attributed to shares, folders and files starting DSM 6.0. Any packages that interact with files on your Synology NAS, these files and folders should have their permissions converted from standard linux permissions to Windows ACLs, and given the proper permissions.

**Comment by Safihre** [comment]
@BenjV @ymartin59 We cannot enforce Windows ACL but we can detect if ACL is used, right? `synoacltool` gives this info, right?
So we could include that as a `preupgrade` check that errors out with an explain-text if we see the share (that we extract from the config, just walk up the dir-tree) isn't ACL?

**Comment by ymartin59** [comment]
Here are some explanation: folder in "transmission/complete" PATH may not be accessible to other users, even if in "sc-download" group because ACL/permissions were too reduce for process/shell/libc to list folder content and traverse. Probably mistake has been done because it was OK in File Station. This is fix in #3216.
For "consumer" services to be able to access any "public" content, their service user will be member of "users" by default.
A service that has both "producer" and "consumer" roles will write with "sc-download" group permission and read thanks to "users" (and also "sc-download") group permission.
What is your opinion about it ?

**Comment by ymartin59** [comment]
@WolfH I have published again Transmission. May you please update and report feedback if your trouble is fixed. Thank you in advance

**Comment by WolfH** [comment]
@ymartin59 I had already fixed my issues earlier on by manually fixing permissions. Installed the update anyway, and it's still working, so that's good. As far as the ACL-talk goes: I'm not using ACL and it's working out great. I'm going to close this issue as it has been fixed (for me at least).

**Comment by Safihre** [comment]
@ymartin59 does this include what you proposed in #3216?

**Comment by BenjV** [comment]
@WolfH 
How do you know you are not using ACL?
If you have a NAS on which the share were configured for the first time with DSM 5 or higher you surely have shares working with ACL's.
Only shares configured before DSM 5 are still not using ACL's.

**Comment by SIRRJ** [comment]
@WolfH I have the same issue you describe but am a complete newbie to this world and would appreciate knowing the steps you took to get this fixed. 

Thanks in advance.

**Comment by jwardle** [comment]
@WolfH @Safihre I'm still experiencing this permission issue after re-installing Transmission 2.93-14 (latest at time of writing) on DSM 6.1.6.

`$ ls -al
drwxrwxrwx+  6            1029 users         4096 Feb  9  2013 .
drwxrwxrwx+ 11 root            users         4096 Apr  2 10:47 ..
drwxrwxrwx+  4 sc-transmission transmission  4096 Apr  2 14:45 complete`

WolfH, would be good to understand what the correct permissions look like so we can replicate. The installation script does not appear to be setting the correct privileges still despite #3216

**Comment by BenjV** [comment]
What's the point in asking the same question on multiple places in this forum?
Not you have to go hunting for the answer.

**Comment by ersefuril** [comment]
I've finally solved this issue by properly setting permissions to the /video folder AND to all subfolders via FileStation.
**sc-download** (and maybe **sc-nzbdrone**, just in case) groups need to have read/write acces.
Do not forget to check the **"apply to all subfolders"** option on the bottom-left corner.

![syno_permissions](https://user-images.githubusercontent.com/4835854/39205336-a13a2014-47fa-11e8-9664-9baf053b0050.png)

**Comment by ForumFerret** [comment]
Aaaand suddenly since middle of last week I'm also seeing Sonarr run as the user 'sc-nzbd+', which as far as I can tell _doesn't exist on the system_ which is a neat trick.

**Comment by BenjV** [comment]
It is there, just not visible to you.
It is hidden from the DSM GUI.

**Comment by Safihre** [comment]
I'd be very surprised if it ran as sabnzbd user. It's more likely that sabnzbd downloaded the file, after which Sonarr moved it (which it can, since they are both in download group) while persevering the original owner as sabnzbd.

**Comment by ForumFerret** [comment]
actually it looks like the user displaying as "sc-nzbd+" is actually an artifact of ps not having enough UID/user space to display sc-nzbdrone.  setting sc-nzbdrone to have read/write access in DSM Files did indeed fix the problem.

**Comment by BenjV** [comment]
If you are using the latest package of the SynoCommunity, then I can tell you that sc-nzbd+ als well as sc-nzbdrone are artifact of the past and should be removed.

The package itself is now running as a "hidden" user and is called sc-nzbdrone which is part of the group sc-download.
You cannot see that user in the DSM GUI, but you should see sc-download.
Permissions to access files and folder should be given via this group sc-download.

**Comment by ymartin59** [comment]
Some properties/permissions UI allow to grant access to hidden service user account (typically in Control Panel / Shared Folder / Permissions), but requires administrative rights.
We recommend permission management thanks to sc-download group, which is allowed from File Station for standard users.

**Comment by ymartin59** [comment]
Please refer to https://github.com/SynoCommunity/spksrc/wiki/Permission-Management

**Comment by mathieu-f** [comment]
If you are still looking for a solution, you just have to add _sc-sickbeard-custom_ user to _transmission_ group :
```
$ sudo synogroup --member transmission my-admin sc-sickbeard-custom sc-transmission
```

Please, note that `synogroup --member` literally set member list, not just add a new user.
So do not forget to check the member list of _transmission_ group before set a new list :
```
$ sudo synogroup --get transmission
Group Name: [transmission]
Group Type: [AUTH_LOCAL]
Group ID:   [190144]
Group Members:
0:[my-admin]
1:[sc-sickbeard-custom]
2:[sc-transmission]
```

Hope this will help.

**Comment by BenjV** [comment]
If you have a group called transmission then either you are using an old version or it is a leftover from a past installation.
So adding these users to that group does not do anything at all unless you have an old transmission or an transmission package from another source.

And please do not use the hiddden users starting with sc- for anything.
Alle privileges can and must be set via the groups sc-media and sc-download.
If accesss is a problem most likely it is because file get permission settings from the folder and the folders were created before the new DSM 6 packages.
So use FileStation to give the groups sc-media and sc-downlod access rights to those folders (recursive)

**Comment by lordvalium** [comment]
I have the same problem. Updated transmission and can not unrar the content downloaded with transmission. 
![ffads](https://user-images.githubusercontent.com/2970225/48282998-83408280-e45b-11e8-8833-1d8b5437ecd2.PNG)

**Comment by BenjV** [comment]
The solution is already write in the post before yours.

**Comment by lordvalium** [comment]
@BenjV  thank you. But i dont really understand it. 
That are my configts, and unrar is still not working. Why is that so complicated? 
![image4](https://user-images.githubusercontent.com/2970225/48299639-2cc15b80-e4d0-11e8-93cf-ef49c39b2499.PNG)
![image3](https://user-images.githubusercontent.com/2970225/48299640-2d59f200-e4d0-11e8-96b3-fa38a580acaf.PNG)
![image2](https://user-images.githubusercontent.com/2970225/48299641-2d59f200-e4d0-11e8-8974-5d290fd36cd2.PNG)
![image1](https://user-images.githubusercontent.com/2970225/48299642-2d59f200-e4d0-11e8-85e5-e8dd85b311dc.PNG)
