### ISSUE TITLE
SABNZBD 32bit not supported by Synology after latest release

### ISSUE THREAD

**Issue by TMidi84** [SynoCommunity/spksrc#4001]
_For new Package Requests, see the guidelines_  

### Setup
SABNZBD
2.3.9-40

_NAS Model: DS918+_ 
_NAS Architecture:_  Intel Celeron J3455
_DSM version:_ 6.2.3-25426

### Expected behavior
Tell us what should happen
When I click "run" on the application, I expect it to start up. 

### Actual behavior
Tell us what happens instead
After latest DSM update SABNZBD application will not start. While the installation is  not new prior to the update I stopped the app in order to prevent it from running for a while. Once the update was completed I have been unable to get the app to start up when I click on the "run" button. 
Reached out to snynology  support and here is their response

```After the DSM update, some of the 32-bit third-party packages will no longer be supported.
The third-party packages in the package center are the latest version that the thrid-party developers had published to us. 
We recommend you to go on to each developer's website and see if they have an updated 64-bit package then use the manual install option in the package center to update the package.
Best,

Derek```
### Steps to reproduce
_1._ stop SABNZBD
_2._ Update DSM to latest release
_3._ Attempt to restart SABNZBD

#### Package log
Unable to attach log file as attachment a DAT file 

_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by hgy59** [comment]
@TMidi84 I have no problems with sabnzbd, but I installed it after update to DSM 6.2.3.
I have tested with Python 2.7.14 and sabnzbd 2.3.9-40. The service is running and I can start the wizard (I never configured a server).

If you want you can test a preview version build on my python 2.7.18 branch (you don't need python 2.7.18).
You find SABNZBd 2.3.9-41 here: https://github.com/hgy59/spksrc/releases/tag/sabnzbd_pre
I have fixed the log file location (use generic log file) in the commit 3e932d348889997df70956ad291aa90b039e0cb6.
I have tested with DS218+ (same arch as DS918+).

**Comment by TMidi84** [comment]
@hgy59  thank for the quick response, the message I am getting  is ```failed to run service package```. Although I have ensured that all necessary permissions are provided and completed a system restart at least 6 times I am still getting that error. Apologies I forgot to add that detail.

**Comment by hgy59** [comment]
@TMidi84 did you try with the version 2.3.9-41 I uploaded for you?
There ___is___ a problem with the current official version (2.3.9-40) as the service and the generic service-start-stop functions write to the same log-file (../var/log/sabnzbd.log).
I fixed this by using the default generic log file (../var/sabnzbd.log) for generic functions.

I can stop and start sabnzbd without any problem.

**Comment by TMidi84** [comment]
So I just decided to uninstall the 2.3.9-40 , because after installing the version you provide it could still not get it run. By uninstalling both, I was able to get to run and I am good now. Thanks for helping out.

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by hgy59** [comment]
@TMidi84 I am happy you solved it. Thanks for the feedback.
