### ISSUE TITLE
ffmpeg7 fails on PPC (Qoric) based Synology

### ISSUE THREAD

**Issue by MarcelDeWit** [SynoCommunity/spksrc#6597]
### Is this a new Bug?

- [x] I checked that the bug hasn't been reported before

### Package Name

ffmpeg

### Package Version

7.0.2-1

### Device Model

DS213+

### Device Architecture

PPC

### Firmware Version

DSM 6.2.4-25556 update 6

### What happened?

After update of TVHeadEnd ffmpeg7 is used. TVHeadEnd fail to run. Error seems to be ffmpeg not able to load libx265.so.209 library.

log from TVH:
Starting tvheadend command tvheadend -f -C -u sc-tvheadend -g tvheadend --http_port 9981 --htsp_port 9982 -c /volume1/@appstore/tvheadend/var -p /volume1/@appstore/tvheadend/var/tvheadend.pid -l /volume1/@appstore/tvheadend/var/tvheadend.log --debug ""
tvheadend: error while loading shared libraries: /var/packages/ffmpeg7/target/lib/libx265.so.209: R_PPC_REL24 relocation at 0x1a70ab74 for symbol `pthread_mutex_init' out of range
tvheadend is not running

Result running ffmpeg7 directly from shell:
ffmpeg7: error while loading shared libraries: /var/packages/ffmpeg7/target/lib/libx265.so.209: R_PPC_REL24 relocation at 0x0aa75b74 for symbol `pthread_mutex_init' out of range

### Reproduction steps

1.  goto dir where ffmpeg7 is installed
2. goto bin dir
3. run ffmpeg7
...

### Install Log

```log
no installer log present
```

### Service Log

```log
no service log present
```

### Other Logs

```log

```

**Comment by MarcelDeWit** [comment]
Device architecture is Qoric (PPC) NOT x86_64, sorry missed that one..

**Comment by Marcel-de-wit** [comment]
This issue seems to be identical to #5323, which was fixed in the x265 Makefile. But now seems to have returned.

**Comment by th0ma7** [comment]
> This issue seems to be identical to [#5323](https://github.com/SynoCommunity/spksrc/pull/5323), which was fixed in the x265 Makefile. But now seems to have returned.

This is a really good catch @Marcel-de-wit and indeed during a code refactoring to ensure `x265` uses a standard cmake build process this particular option was removed: https://github.com/SynoCommunity/spksrc/pull/6002/commits/ce1fad8c3ea2980eef4694cca73a33e9ec4c84b1

I'll look at fixing this, thnx for the finding.

**Comment by th0ma7** [comment]
Fix in PR #6598 - Once the github-action build completes if you don't mind testing it out?  thnx.

**Comment by Marcel-de-wit** [comment]
Thanks for the quick fix. I am happy to test it out on my DS213+ this weekend.

**Comment by MarcelDeWit** [comment]
I just testen the ffmpeg7 package. unfortunately the error remains.

./ffmpeg: error while loading shared libraries: /var/packages/ffmpeg7/target/lib/libx265.so.209: R_PPC_REL24 relocation at 0x0aa75b74 for symbol `pthread_mutex_init' out of range.

The build of the libx265 library in the ffmpeg7 package seems not te be updated:

/var/packages/ffmpeg7/target/lib$ ls -l libx*
lrwxrwxrwx 1 root root      14 Oct  3  2024 libx264.so -> libx264.so.164
-rwxr-xr-x 1 root root 2015260 Oct  3  2024 libx264.so.164
lrwxrwxrwx 1 root root      14 Oct  3  2024 libx265.so -> libx265.so.209
-rw-r--r-- 1 root root 7575572 Oct  3  2024 libx265.so.209
lrwxrwxrwx 1 root root      17 Oct  3  2024 libxml2.so -> libxml2.so.2.9.14
lrwxrwxrwx 1 root root      17 Oct  3  2024 libxml2.so.2 -> libxml2.so.2.9.14
-rwxr-xr-x 1 root root 1781344 Oct  3  2024 libxml2.so.2.9.14

**Comment by th0ma7** [comment]
@MarcelDeWit have you download the qoriq package from the github test-build at https://github.com/SynoCommunity/spksrc/actions/runs/15478541718 then installed it manually from the package center?

EDIT: And must unzip the download file first, you only need to install the ffmpeg7 spk file from the package center.

**Comment by MarcelDeWit** [comment]
Yep, that the one I used. But it hasn't the latest build of libx265 inside.

**Comment by th0ma7** [comment]
@MarcelDeWit this got me curious so I downloaded the qoriq package, untar'ed it, unzip'ed the internal `package.tgz` and listed files: 
```
$ ll lib/libx265.so*
lrwxrwxrwx 1 th0ma7 th0ma7      14 jun  5 19:43 lib/libx265.so -> libx265.so.209
-rw-r--r-- 1 th0ma7 th0ma7 6773912 jun  5 19:56 lib/libx265.so.209
```
Clearly you must have re-installed the original published package from our synocommunity.com website rather than the github PR autobuild package.

Go here: https://github.com/SynoCommunity/spksrc/actions/runs/15478541718
You'll find a qoriq package which as the following URL: https://github.com/SynoCommunity/spksrc/actions/runs/15478541718/artifacts/3272191961

unzip that file, inside it you'll find the ffmpeg7 spk package to install, thnx!

**Comment by Marcel-de-wit** [comment]
Ah... I must have downloaded from the wrong github location. I will try again tonight.

**Comment by MarcelDeWit** [comment]
Took a little bit longer, sorry. But I have both ffmpeg7 and TVHeadEnd up and running again on my DS213!

(must have downloaded previous version just a bit too early from github while the build did nog contain the fix yet)

**Comment by th0ma7** [comment]
Good, any issue?

**Comment by MarcelDeWit** [comment]
No. Everything worked as it should. 
 installed ffmpeg7 first, then TvHeadEnd.
Both work. And I tested ffmpeg7 on the shell.

Thanks!
